### ISSUE TITLE
Support for FAWE per-player schematics

### ISSUE THREAD

**Issue by TomLewis** [Dinty1/DiscordSchematicUploader#9]
FAWE uses `per-player-schematics: true` which creates a folder per player for their schematics, this could easily follow suite for discord linked players as it will have access to their UUID.

**Comment by Dinty1** [comment]
It doesn't currently, but this has been suggested before so I'll look into adding.

**Comment by Dinty1** [comment]
I'm not an FAWE user so I may be missing something here, but does the system just work by having a subdirectory named after the player's uuid within the schematics folder?
